import torch
from .base import BaseDiffusionModel

class DummyDiffusionModel(BaseDiffusionModel):
    """
    A dummy diffusion model that doesn't actually have a neural network.
    It simulates the process by just adding Gaussian noise and then 
    adding another random noise in reverse to 'hallucinate' slightly 
    different data, thus performing simple data augmentation.
    """
    def __init__(self, noise_scale: float = 0.1):
        self.noise_scale = noise_scale

    def forward_diffusion(self, x: torch.Tensor, t: int) -> torch.Tensor:
        """
        Simulate adding noise `t` times. We just scale the noise based on `t`.
        """
        noise = torch.randn_like(x) * self.noise_scale * (t / 10.0)
        return x + noise

    def reverse_diffusion(self, x_t: torch.Tensor, steps: int) -> torch.Tensor:
        """
        Simulate the reverse process. Instead of perfectly reconstructing, 
        we add a tiny bit of structural 'generation' noise to simulate 
        the diversity generated by a real diffusion model.
        """
        # A real diffusion model would denoise x_t using a UNet or similar.
        # Here we just return x_t with slight smoothing or random variance 
        # to simulate the generated output.
        generation_noise = torch.randn_like(x_t) * self.noise_scale * 0.5
        return x_t + generation_noise
